name: Detect Changed Folders

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get list of changed folders
        id: changed_folders
        run: |
          # Get list of changed files and extract unique directories
          changed_dirs=$(git diff --name-only ${{ github.sha }} ${{ github.sha }}~1 | cut -d'/' -f1 | sort -u)
          echo "$changed_dirs"
          echo "::set-output name=dirs::$changed_dirs"

      - name: Output changed folders
        run: |
          for dir in ${{ steps.changed_folders.outputs.dirs }}; do
            echo "Changed folders: ${{ steps.changed_folders.outputs.dirs }}"
          done